### ISSUE TITLE
Not all unavailable entities being detected

### ISSUE THREAD

**Issue by Bytelink5616** [jazzyisj/unavailable-entities-sensor#2]
First thanks for this wonderful package.  I am sure I am doing something wrong because it seems if the device is unavailable when I restart HA then the device is not seen as unavailable and the sensor value is 0. If however the device changes to unavailable when HA is running I get the notification as expected and the sensor value changes to the value expected.  At the moment I am just using your sample automation. Also if you do not mind if I wanted to make another sensor to just monitor my lights is this possible? Once again thanks for this package. I attached a couple of screenshots showing that there unavailable entities and the value of the sensor.
![states](https://user-images.githubusercontent.com/84490871/147528800-60bf1a42-beff-429e-a6f7-6e268f1ccd1e.jpg)
![sensor value](https://user-images.githubusercontent.com/84490871/147528803-493fcf15-5a43-4848-9ea7-62dea65565fe.jpg)

**Comment by jazzyisj** [comment]
Let me answer your question about the lights first because I have that answer ready to go.  Of course!

https://github.com/jazzyisj/unavailable-entities-sensor#include-domains-instead-of-exlude
I just realized I can improve the README a bit because there is a better way as outlined below if you only want to monitor one domain.  If you want to monitor more than one domain you must use the method currently shown in the README.

Add this sensor right between the original sensor and the group declaration in the package.  Note that this will use the same ignored_entities as your main unavailable entities sensor.  You can remove that filter (`|rejectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))`)  if you don't want to use that group for this sensor or you can create an entirely separate group if you have any light entities you want to ignore (for example if you're using light groups that would duplicate existing unavailable lights or template lights that are not applicable).

What this template does is limits the states object to just the light domain (`states.light`) and removes the group domain rejectattr filter (it is now pointless as we are only monitoring the light domain.)

```
  - sensor:
      - unique_id: unavailable_lights
        name: 'Unavailable Lights'
        unit_of_measurement: lights
        state: >
          {% if state_attr('sensor.unavailable_lights','entities') != none %}
            {{ state_attr('sensor.unavailable_lights','entities')|count }}
          {% endif %}
        attributes:
          entities: >
            {% set ignore_seconds = 60 %}
            {% set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}
            {{ states.light
              |rejectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))
              |rejectattr('last_changed','lt',ignore_ts)
              |selectattr('state','in',['unavailable','unknown','none'])|map(attribute='entity_id')|list }}
```

As for your other question, I'm doing some experimenting to see if I can duplicate your startup issue.  I definitely do not see that condition.  Here is the sensor showing unavailable entities during startup on my system.

![image](https://user-images.githubusercontent.com/44064559/147569976-d8cec488-3984-4d6e-9ccf-9c642a6ae71f.png)

Last but not least, if you are using Windows look into the "Snipping Tool".  That tool allows you to take snips of only the relevant portion of your screen to share (like I did above) instead of taking a snapshot of your whole screen.

**Comment by jazzyisj** [comment]
> I am sure I am doing something wrong

Pretty sure it is me and not you!  You just discovered the bug!  I'm glad you caught it before too many people came across the repository..lol.  Anyway, at some point I changed the filters around and forgot to reverse the timestamp test on my repository copy of the sensor.  That means the sensor was rejecting all entities with a last changed time of LESS than the ignored timestamp which is the exact off opposite of what we want!  Ugh.

Change this line

    |rejectattr('last_changed','lt',ignore_ts)

to

    |rejectattr('last_changed','ge',ignore_ts)

Does this resolve your problem at startup?

**Comment by Bytelink5616** [comment]
I am not able to test it till later today but will let you know

Thanks

**Comment by Bytelink5616** [comment]
Yes thank you. This solved the problem they all seem to report fine now. One more trivial thing you may be able to help me with is the format of my persistent message. I can’t seem to work out why there is no – in front of the first entry.

Ian

**Comment by jazzyisj** [comment]
![image](https://user-images.githubusercontent.com/44064559/147679132-3e2ae687-bfbe-4b36-b93a-cc4cc3908bea.png)
This is the first hyphen.  Does that exist in your code?

**Comment by Bytelink5616** [comment]
Thankyou. That was it. I had copied the message but when I saved it the UI removed the quotes and the hyphen. I had to use file editor in the end to edit the message and save it and then it worked fine.  I am not sure why the UI does what it does but I found a work around.  Once again thanks for the help and the wondeful sensor it works like a charm.

Ian
