### ISSUE TITLE
Wrong state reported by unavailable entities

### ISSUE THREAD

**Issue by roydestroy** [jazzyisj/unavailable-entities-sensor#58]
The state of the sensor shows 1 even though I have 2 or more unavailable entities. 

Photos attached
![Screenshot 2024-12-16 032327](https://github.com/user-attachments/assets/e92ab4f9-8607-4ca5-b816-450bedbec650)
![Screenshot 2024-12-16 032252](https://github.com/user-attachments/assets/f31fe8e9-466f-4aa3-a632-0cb4e943955f)
And still the same problem after the update
![image](https://github.com/user-attachments/assets/5ffbf2ac-61dd-4e68-b568-69174dbe63cb)
![image](https://github.com/user-attachments/assets/4585cbd1-10b0-486f-a97a-353fb00679ce)

**Comment by jazzyisj** [comment]
What version of the package are you using?  The new version of the sensor now only updates once per minute so it can take up to a minute for the sensor state to update.  If that is an issue for some reason you can increase the update frequency.

**Comment by roydestroy** [comment]
I am using the latest, and this has apparently nothing to do with the automation because initially it shows the correct number of entities and after some time it goes back to 1

**Comment by roydestroy** [comment]
I mean look at this, the history and current state shows always 2 but the number in the state is 1
![image](https://github.com/user-attachments/assets/b055136e-6d11-45e5-a445-5c8fe70a0d3f)

**Comment by jazzyisj** [comment]
That is strange.  But at the end of the day, this is really just a simple template sensor.   There is nothing about it that should have any affect on how it is treated by the database / history.  

I have the base package with no modifications installed on my system and everything is as it should be.  I even manually counted up the unavailable entities to verify the entity count.  I am trying to come up with some sort of explanation for what you are seeing and I am at a total loss.
Other than this anomaly with the history, is everything else about the sensor working correctly?  Is the state reporting the correct value?  In the screenshot above, was there actually only 1 entity that was unavailable or unknown?  I noticed that in all your screenshots the state is always reported as 1, not sure if that is a coincidence or not. 



As long as the state reported by sensor.unavailable_entities is equal to the number of entities in group.unavailable_entities then everything is working correctly.  That is all the sensor does, it counts the number of items in the the entity_id attribute of the unavailable entities group.  

The only anomaly you may see is it may take up to a minute for an unavailable entity to appear in the group and it may take up to a minute for an entity to be removed from the group when it becomes available.  That is by design to throttle the template updates.

<img width="511" alt="image" src="https://github.com/user-attachments/assets/7b0f62bc-2355-4656-89fa-dc7de6da984d" />

<img width="809" alt="image" src="https://github.com/user-attachments/assets/12775d1d-20b5-49c4-8601-90c897f5aef3" />

**Comment by jazzyisj** [comment]
Did you get this figured out?  Not sure what else I can do to help you here.
